language: node_js
node_js:
- '8'
sudo: false
notifications:
  email:
    recipients:
    - steven@stevenweaver.org
    on_success: always
    on_failure: always

branches:
  only:
  - master
  - develop

cache:
  yarn: true
  directories:
  - ".eslintcache"
  - node_modules

script:
  - yarn build:library
  - yarn run jest
